blank_issues_enabled: false
contact_links:
  - name: "âœ¨ Feature Requests"
    about: "We now accept feature requests only through Discord!"
    url: "https://discord.com/channels/376425582139015168/1293179465160986746/1293179465160986746"
  - name: "ğŸ› ï¸ Get Support"
    about: "Need help? Join our Discord Server for assistance!"
    url: "https://discord.gg/advancedplugins"
